#include "codegen_internal.h"

#include <sstream>
#include <string>

namespace vortex::codegen_internal {

std::string generate_source(const std::string& ident, const std::string& user_name) {
  std::ostringstream out;
  std::string prefix = ident + "_vortex";
  std::string escaped_name = escape_c_string(user_name);
  out << "#include \"" << ident << ".h\"\n\n";
  out << "#include <algorithm>\n";
  out << "#include <cmath>\n";
  out << "#include <cstddef>\n";
  out << "#include <cstring>\n";
  out << "#include <fstream>\n";
  out << "#include <limits>\n";
  out << "#include <stdexcept>\n\n";
  out << "#include <vector>\n\n";
  out << "#if defined(__AVX2__)\n";
  out << "#include <immintrin.h>\n";
  out << "#elif defined(__ARM_NEON) || defined(__ARM_NEON__)\n";
  out << "#include <arm_neon.h>\n";
  out << "#endif\n\n";
  out << "namespace vortex_codegen {\n";
  out << "namespace " << ident << " {\n\n";
  out << "constexpr const char* kDefaultModelFile = \"model.bin\";\n\n";
  out << "constexpr const char* kDefaultCentroidIndexFile = \"centroid_index.bin\";\n";
  out << "constexpr uint32_t kDefaultCentroidIndexPivots = 16;\n\n";
  out << "constexpr std::size_t kDirectScanThresholdDim32 = 256;\n";
  out << "constexpr std::size_t kDirectScanThresholdDim64 = 512;\n\n";
  out << "constexpr char kCentroidIndexMagic[8] = {'V','T','X','C','I','1','\\0','\\0'};\n";
  out << "constexpr uint32_t kCentroidIndexVersion = 1;\n\n";
  out << "struct CentroidIndexHeader {\n";
  out << "  char magic[8];\n";
  out << "  uint32_t version = 0;\n";
  out << "  uint32_t dim = 0;\n";
  out << "  uint32_t centroid_count = 0;\n";
  out << "  uint32_t active_count = 0;\n";
  out << "  uint32_t pivot_count = 0;\n";
  out << "};\n\n";
  out << "static double dot_product(const float* a, const float* b, uint32_t dim) {\n";
  out << "  std::size_t d = 0;\n";
  out << "  double sum = 0.0;\n";
  out << "#if defined(__AVX2__)\n";
  out << "  __m256 acc = _mm256_setzero_ps();\n";
  out << "  for (; d + 8 <= dim; d += 8) {\n";
  out << "    __m256 va = _mm256_loadu_ps(a + d);\n";
  out << "    __m256 vb = _mm256_loadu_ps(b + d);\n";
  out << "    acc = _mm256_add_ps(acc, _mm256_mul_ps(va, vb));\n";
  out << "  }\n";
  out << "  alignas(32) float tmp[8];\n";
  out << "  _mm256_store_ps(tmp, acc);\n";
  out << "  for (int i = 0; i < 8; ++i) sum += static_cast<double>(tmp[i]);\n";
  out << "#elif defined(__ARM_NEON) || defined(__ARM_NEON__)\n";
  out << "  float32x4_t acc = vdupq_n_f32(0.0f);\n";
  out << "  for (; d + 4 <= dim; d += 4) {\n";
  out << "    float32x4_t va = vld1q_f32(a + d);\n";
  out << "    float32x4_t vb = vld1q_f32(b + d);\n";
  out << "    acc = vmlaq_f32(acc, va, vb);\n";
  out << "  }\n";
  out << "  alignas(16) float tmp[4];\n";
  out << "  vst1q_f32(tmp, acc);\n";
  out << "  sum += static_cast<double>(tmp[0] + tmp[1] + tmp[2] + tmp[3]);\n";
  out << "#endif\n";
  out << "  for (; d < dim; ++d) {\n";
  out << "    sum += static_cast<double>(a[d]) * static_cast<double>(b[d]);\n";
  out << "  }\n";
  out << "  return sum;\n";
  out << "}\n\n";
  out << "static double l2_norm2(const float* a, uint32_t dim) {\n";
  out << "  return dot_product(a, a, dim);\n";
  out << "}\n\n";
  out << "static double l2_dist2_from_dot(double q_norm2, double c_norm2, double dot_qc) {\n";
  out << "  double d2 = q_norm2 + c_norm2 - 2.0 * dot_qc;\n";
  out << "  if (d2 < 0.0) {\n";
  out << "    d2 = 0.0;\n";
  out << "  }\n";
  out << "  return d2;\n";
  out << "}\n\n";
  out << "static double l2_dist2(const float* a, const float* b, uint32_t dim) {\n";
  out << "  double acc = 0.0;\n";
  out << "  for (uint32_t d = 0; d < dim; ++d) {\n";
  out << "    double diff = static_cast<double>(a[d]) - static_cast<double>(b[d]);\n";
  out << "    acc += diff * diff;\n";
  out << "  }\n";
  out << "  return acc;\n";
  out << "}\n\n";
  out << "static std::filesystem::path resolve_model_path(const char* path) {\n";
  out << "  if (!path || std::strlen(path) == 0) {\n";
  out << "    return std::filesystem::path(kDefaultModelFile);\n";
  out << "  }\n";
  out << "  std::filesystem::path candidate(path);\n";
  out << "  if (std::filesystem::exists(candidate) && std::filesystem::is_directory(candidate)) {\n";
  out << "    return candidate / kDefaultModelFile;\n";
  out << "  }\n";
  out << "  return candidate;\n";
  out << "}\n\n";
  out << "static std::filesystem::path resolve_index_path(const std::filesystem::path& model_path) {\n";
  out << "  std::filesystem::path dir = model_path.parent_path();\n";
  out << "  if (dir.empty()) {\n";
  out << "    return std::filesystem::path(kDefaultCentroidIndexFile);\n";
  out << "  }\n";
  out << "  return dir / kDefaultCentroidIndexFile;\n";
  out << "}\n\n";
  out << "struct AnnHeapEntry {\n";
  out << "  double dist2 = 0.0;\n";
  out << "  uint32_t centroid = 0;\n";
  out << "};\n\n";
  out << "struct QueryPivotCacheState {\n";
  out << "  const Hasher* owner = nullptr;\n";
  out << "  const float* query_ptr = nullptr;\n";
  out << "  double query_norm2 = 0.0;\n";
  out << "  uint64_t token = 0;\n";
  out << "  std::vector<double> pivot_l2;\n";
  out << "  std::vector<AnnNeighbor> ann_full_scan;\n";
  out << "  std::vector<AnnHeapEntry> ann_heap;\n";
  out << "};\n\n";
  out << "static QueryPivotCacheState& tls_query_pivot_cache() {\n";
  out << "  static thread_local QueryPivotCacheState state;\n";
  out << "  return state;\n";
  out << "}\n\n";
  out << "static uint64_t next_cache_token(uint64_t token) {\n";
  out << "  return token == std::numeric_limits<uint64_t>::max() ? 1 : (token + 1);\n";
  out << "}\n\n";
  out << "static void invalidate_query_pivot_cache(const Hasher* owner) {\n";
  out << "  auto& state = tls_query_pivot_cache();\n";
  out << "  if (!owner || state.owner == owner) {\n";
  out << "    state.owner = nullptr;\n";
  out << "    state.query_ptr = nullptr;\n";
  out << "    state.query_norm2 = 0.0;\n";
  out << "    state.token = 0;\n";
  out << "  }\n";
  out << "}\n\n";
  out << "void Hasher::clear_active_centroids() {\n";
  out << "  active_ids_.clear();\n";
  out << "  active_vectors_.clear();\n";
  out << "  active_norm2_.clear();\n";
  out << "  centroid_norm2_.clear();\n";
  out << "}\n\n";
  out << "void Hasher::clear_centroid_index() {\n";
  out << "  invalidate_query_pivot_cache(this);\n";
  out << "  index_active_ids_.clear();\n";
  out << "  index_active_vectors_.clear();\n";
  out << "  index_active_norm2_.clear();\n";
  out << "  index_pivot_ids_.clear();\n";
  out << "  index_pivot_vectors_.clear();\n";
  out << "  index_pivot_norm2_.clear();\n";
  out << "  index_centroid_pivot_l2_.clear();\n";
  out << "}\n\n";
  out << "void Hasher::populate_centroid_buffers(const std::vector<uint32_t>& ids,\n";
  out << "                                      AlignedVector<float>* vectors,\n";
  out << "                                      std::vector<double>* norm2) const {\n";
  out << "  if (!vectors || !norm2) {\n";
  out << "    return;\n";
  out << "  }\n";
  out << "  std::size_t dim = static_cast<std::size_t>(model_.dim);\n";
  out << "  vectors->resize(ids.size() * dim);\n";
  out << "  norm2->resize(ids.size());\n";
  out << "  for (std::size_t i = 0; i < ids.size(); ++i) {\n";
  out << "    uint32_t cid = ids[i];\n";
  out << "    const float* src = model_.centroids.data() + static_cast<std::size_t>(cid) * dim;\n";
  out << "    float* dst = vectors->data() + i * dim;\n";
  out << "    std::memcpy(dst, src, dim * sizeof(float));\n";
  out << "    (*norm2)[i] = centroid_norm2_[cid];\n";
  out << "  }\n";
  out << "}\n\n";
  out << "const std::vector<double>& Hasher::prepare_query_pivot_l2(\n";
  out << "    const float* vector,\n";
  out << "    double query_norm2,\n";
  out << "    uint64_t input_cache_token,\n";
  out << "    uint64_t* out_cache_token,\n";
  out << "    bool allow_cache_without_output) const {\n";
  out << "  std::size_t pivot_count = index_pivot_ids_.size();\n";
  out << "  auto& cache_state = tls_query_pivot_cache();\n";
  out << "  bool query_cache_allowed = query_cache_enabled_ &&\n";
  out << "      (out_cache_token || allow_cache_without_output);\n";
  out << "  bool reused_cache = query_cache_allowed &&\n";
  out << "      input_cache_token != 0 &&\n";
  out << "      cache_state.owner == this &&\n";
  out << "      cache_state.query_ptr == vector &&\n";
  out << "      cache_state.query_norm2 == query_norm2 &&\n";
  out << "      cache_state.token == input_cache_token &&\n";
  out << "      cache_state.pivot_l2.size() == pivot_count;\n";
  out << "  if (!reused_cache) {\n";
  out << "    if (cache_state.pivot_l2.size() < pivot_count) {\n";
  out << "      cache_state.pivot_l2.resize(pivot_count, 0.0);\n";
  out << "    }\n";
  out << "    for (std::size_t p = 0; p < pivot_count; ++p) {\n";
  out << "      const float* pivot_vec = index_pivot_vectors_.data() + p * static_cast<std::size_t>(model_.dim);\n";
  out << "      double dot_qp = dot_product(vector, pivot_vec, model_.dim);\n";
  out << "      double pivot_d2 = l2_dist2_from_dot(query_norm2, index_pivot_norm2_[p], dot_qp);\n";
  out << "      cache_state.pivot_l2[p] = std::sqrt(pivot_d2);\n";
  out << "    }\n";
  out << "    if (query_cache_allowed) {\n";
  out << "      cache_state.owner = this;\n";
  out << "      cache_state.query_ptr = vector;\n";
  out << "      cache_state.query_norm2 = query_norm2;\n";
  out << "      cache_state.token = next_cache_token(cache_state.token);\n";
  out << "    } else {\n";
  out << "      cache_state.owner = nullptr;\n";
  out << "      cache_state.query_ptr = nullptr;\n";
  out << "      cache_state.query_norm2 = 0.0;\n";
  out << "      cache_state.token = 0;\n";
  out << "    }\n";
  out << "  }\n";
  out << "  if (out_cache_token) {\n";
  out << "    *out_cache_token = query_cache_allowed ? cache_state.token : 0;\n";
  out << "  }\n";
  out << "  return cache_state.pivot_l2;\n";
  out << "}\n\n";
  out << "void Hasher::prepare_active_centroids() {\n";
  out << "  clear_active_centroids();\n";
  out << "  if (!loaded_ || model_.dim == 0 || model_.centroids.empty()) {\n";
  out << "    return;\n";
  out << "  }\n";
  out << "  std::size_t count = model_.centroid_count();\n";
  out << "  centroid_norm2_.resize(count);\n";
  out << "  for (std::size_t i = 0; i < count; ++i) {\n";
  out << "    const float* c = model_.centroids.data() + i * model_.dim;\n";
  out << "    centroid_norm2_[i] = l2_norm2(c, model_.dim);\n";
  out << "  }\n";
  out << "  const auto& active = model_.router.active_centroids();\n";
  out << "  if (!active.empty()) {\n";
  out << "    active_ids_ = active;\n";
  out << "  } else {\n";
  out << "    active_ids_.resize(count);\n";
  out << "    for (std::size_t i = 0; i < count; ++i) {\n";
  out << "      active_ids_[i] = static_cast<uint32_t>(i);\n";
  out << "    }\n";
  out << "  }\n";
  out << "  populate_centroid_buffers(active_ids_, &active_vectors_, &active_norm2_);\n";
  out << "}\n\n";
  out << "bool Hasher::load_centroid_index(const std::filesystem::path& index_path,\n";
  out << "                                uint32_t expected_pivots) {\n";
  out << "  clear_centroid_index();\n";
  out << "  if (!loaded_ || active_ids_.empty()) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::ifstream in(index_path, std::ios::binary);\n";
  out << "  if (!in) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  CentroidIndexHeader header{};\n";
  out << "  in.read(reinterpret_cast<char*>(&header), static_cast<std::streamsize>(sizeof(header)));\n";
  out << "  if (!in) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (std::memcmp(header.magic, kCentroidIndexMagic, sizeof(header.magic)) != 0 ||\n";
  out << "      header.version != kCentroidIndexVersion ||\n";
  out << "      header.dim != model_.dim ||\n";
  out << "      header.centroid_count != static_cast<uint32_t>(model_.centroid_count()) ||\n";
  out << "      header.active_count != static_cast<uint32_t>(active_ids_.size()) ||\n";
  out << "      header.pivot_count == 0) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (expected_pivots != 0 && header.pivot_count != expected_pivots) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::size_t active_count = header.active_count;\n";
  out << "  std::size_t pivot_count = header.pivot_count;\n";
  out << "  if (pivot_count > static_cast<std::size_t>(std::numeric_limits<uint32_t>::max())) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (active_count > 0 && pivot_count > (std::numeric_limits<std::size_t>::max() / active_count)) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::size_t dim = static_cast<std::size_t>(model_.dim);\n";
  out << "  if ((active_count > 0 && dim > (std::numeric_limits<std::size_t>::max() / active_count)) ||\n";
  out << "      (pivot_count > 0 && dim > (std::numeric_limits<std::size_t>::max() / pivot_count))) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::vector<uint32_t> file_active(active_count);\n";
  out << "  std::vector<uint32_t> file_pivots(pivot_count);\n";
  out << "  AlignedVector<float> file_l2(active_count * pivot_count);\n";
  out << "  in.read(reinterpret_cast<char*>(file_active.data()),\n";
  out << "          static_cast<std::streamsize>(file_active.size() * sizeof(uint32_t)));\n";
  out << "  in.read(reinterpret_cast<char*>(file_pivots.data()),\n";
  out << "          static_cast<std::streamsize>(file_pivots.size() * sizeof(uint32_t)));\n";
  out << "  in.read(reinterpret_cast<char*>(file_l2.data()),\n";
  out << "          static_cast<std::streamsize>(file_l2.size() * sizeof(float)));\n";
  out << "  if (!in) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (file_active != active_ids_) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::size_t centroid_count = model_.centroid_count();\n";
  out << "  for (uint32_t cid : file_pivots) {\n";
  out << "    if (cid >= centroid_count) {\n";
  out << "      return false;\n";
  out << "    }\n";
  out << "  }\n";
  out << "  index_active_ids_ = std::move(file_active);\n";
  out << "  index_pivot_ids_ = std::move(file_pivots);\n";
  out << "  index_centroid_pivot_l2_ = std::move(file_l2);\n";
  out << "  populate_centroid_buffers(index_active_ids_, &index_active_vectors_, &index_active_norm2_);\n";
  out << "  populate_centroid_buffers(index_pivot_ids_, &index_pivot_vectors_, &index_pivot_norm2_);\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "bool Hasher::load(const std::filesystem::path& model_path,\n";
  out << "                  const LoadOptions& options) {\n";
  out << "  invalidate_query_pivot_cache(this);\n";
  out << "  model_ = vortex::VortexModel::read(model_path);\n";
  out << "  loaded_ = true;\n";
  out << "  prepare_active_centroids();\n";
  out << "  centroid_index_enabled_ = options.enable_centroid_index && should_consider_centroid_index();\n";
  out << "  query_cache_enabled_ = options.enable_query_cache;\n";
  out << "  clear_centroid_index();\n";
  out << "  if (centroid_index_enabled_) {\n";
  out << "    uint32_t pivots = options.centroid_index_pivots == 0\n";
  out << "        ? kDefaultCentroidIndexPivots\n";
  out << "        : options.centroid_index_pivots;\n";
  out << "    std::filesystem::path index_path = resolve_index_path(model_path);\n";
  out << "    if (!load_centroid_index(index_path, pivots)) {\n";
  out << "      build_centroid_index(pivots);\n";
  out << "    }\n";
  out << "  }\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "bool Hasher::load_from_dir(const std::filesystem::path& dir,\n";
  out << "                          const LoadOptions& options) {\n";
  out << "  return load(dir / kDefaultModelFile, options);\n";
  out << "}\n\n";
  out << "void Hasher::build_centroid_index(uint32_t pivot_count) {\n";
  out << "  clear_centroid_index();\n";
  out << "  if (!loaded_ || active_ids_.empty()) {\n";
  out << "    return;\n";
  out << "  }\n";
  out << "  index_active_ids_ = active_ids_;\n";
  out << "  index_active_vectors_ = active_vectors_;\n";
  out << "  index_active_norm2_ = active_norm2_;\n";
  out << "\n";
  out << "  std::size_t active_count = index_active_ids_.size();\n";
  out << "  std::size_t pivots = static_cast<std::size_t>(pivot_count == 0 ? 1 : pivot_count);\n";
  out << "  if (pivots > active_count) {\n";
  out << "    pivots = active_count;\n";
  out << "  }\n";
  out << "\n";
  out << "  index_pivot_ids_.reserve(pivots);\n";
  out << "  index_pivot_ids_.push_back(index_active_ids_.front());\n";
  out << "  if (pivots > 1) {\n";
  out << "    std::vector<double> min_d2(active_count, std::numeric_limits<double>::infinity());\n";
  out << "    const float* first = index_active_vectors_.data();\n";
  out << "    for (std::size_t i = 0; i < active_count; ++i) {\n";
  out << "      const float* candidate = index_active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "      min_d2[i] = l2_dist2(candidate, first, model_.dim);\n";
  out << "    }\n";
  out << "    while (index_pivot_ids_.size() < pivots) {\n";
  out << "      std::size_t best_pos = 0;\n";
  out << "      double best_val = -1.0;\n";
  out << "      for (std::size_t i = 0; i < active_count; ++i) {\n";
  out << "        if (min_d2[i] > best_val) {\n";
  out << "          best_val = min_d2[i];\n";
  out << "          best_pos = i;\n";
  out << "        }\n";
  out << "      }\n";
  out << "      uint32_t pivot_id = index_active_ids_[best_pos];\n";
  out << "      index_pivot_ids_.push_back(pivot_id);\n";
  out << "      const float* pivot_vec = model_.centroids.data() + static_cast<std::size_t>(pivot_id) * model_.dim;\n";
  out << "      for (std::size_t i = 0; i < active_count; ++i) {\n";
  out << "        const float* candidate = index_active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "        double d2 = l2_dist2(candidate, pivot_vec, model_.dim);\n";
  out << "        if (d2 < min_d2[i]) {\n";
  out << "          min_d2[i] = d2;\n";
  out << "        }\n";
  out << "      }\n";
  out << "    }\n";
  out << "  }\n";
  out << "\n";
  out << "  populate_centroid_buffers(index_pivot_ids_, &index_pivot_vectors_, &index_pivot_norm2_);\n";
  out << "\n";
  out << "  std::size_t pivot_count_sz = index_pivot_ids_.size();\n";
  out << "  index_centroid_pivot_l2_.resize(active_count * pivot_count_sz);\n";
  out << "  for (std::size_t i = 0; i < active_count; ++i) {\n";
  out << "    const float* active_vec = index_active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "    for (std::size_t p = 0; p < pivot_count_sz; ++p) {\n";
  out << "      const float* pivot_vec = index_pivot_vectors_.data() + p * static_cast<std::size_t>(model_.dim);\n";
  out << "      double d2 = l2_dist2(active_vec, pivot_vec, model_.dim);\n";
  out << "      index_centroid_pivot_l2_[i * pivot_count_sz + p] = static_cast<float>(std::sqrt(d2));\n";
  out << "    }\n";
  out << "  }\n";
  out << "}\n\n";
  out << "void Hasher::unload() {\n";
  out << "  invalidate_query_pivot_cache(this);\n";
  out << "  model_ = vortex::VortexModel();\n";
  out << "  clear_centroid_index();\n";
  out << "  clear_active_centroids();\n";
  out << "  centroid_index_enabled_ = true;\n";
  out << "  query_cache_enabled_ = true;\n";
  out << "  loaded_ = false;\n";
  out << "}\n\n";
  out << "bool Hasher::loaded() const { return loaded_; }\n\n";
  out << "bool Hasher::centroid_index_enabled() const {\n";
  out << "  std::size_t dim = static_cast<std::size_t>(model_.dim);\n";
  out << "  if ((index_active_ids_.size() > 0 && dim > (std::numeric_limits<std::size_t>::max() / index_active_ids_.size())) ||\n";
  out << "      (index_pivot_ids_.size() > 0 && dim > (std::numeric_limits<std::size_t>::max() / index_pivot_ids_.size()))) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::size_t active_expected = index_active_ids_.size() * dim;\n";
  out << "  std::size_t pivot_expected = index_pivot_ids_.size() * dim;\n";
  out << "  return centroid_index_enabled_ &&\n";
  out << "         !index_active_ids_.empty() &&\n";
  out << "         !index_pivot_ids_.empty() &&\n";
  out << "         index_active_vectors_.size() == active_expected &&\n";
  out << "         index_active_ids_.size() == index_active_norm2_.size() &&\n";
  out << "         index_pivot_vectors_.size() == pivot_expected &&\n";
  out << "         index_pivot_ids_.size() == index_pivot_norm2_.size();\n";
  out << "}\n\n";
  out << "bool Hasher::query_cache_enabled() const {\n";
  out << "  return query_cache_enabled_;\n";
  out << "}\n\n";
  out << "bool Hasher::should_consider_centroid_index() const {\n";
  out << "  std::size_t active_count = active_ids_.size();\n";
  out << "  if (active_count == 0) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (model_.dim >= 64 && active_count <= kDirectScanThresholdDim64) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (model_.dim >= 32 && active_count <= kDirectScanThresholdDim32) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "bool Hasher::use_centroid_index_for_queries() const {\n";
  out << "  if (!centroid_index_enabled() || !should_consider_centroid_index()) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "bool Hasher::nearest_centroid(const float* vector,\n";
  out << "                             uint32_t* centroid,\n";
  out << "                             double* dist2,\n";
  out << "                             uint64_t* cache_token) const {\n";
  out << "  if (!loaded_ || !vector || !centroid || !dist2 || active_ids_.empty()) {\n";
  out << "    if (cache_token) {\n";
  out << "      *cache_token = 0;\n";
  out << "    }\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  double query_norm2 = l2_norm2(vector, model_.dim);\n";
  out << "  if (!std::isfinite(query_norm2)) {\n";
  out << "    if (cache_token) {\n";
  out << "      *cache_token = 0;\n";
  out << "    }\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (!use_centroid_index_for_queries() ||\n";
  out << "      index_centroid_pivot_l2_.size() != index_active_ids_.size() * index_pivot_ids_.size()) {\n";
  out << "    double best_d2 = std::numeric_limits<double>::infinity();\n";
  out << "    uint32_t best_id = active_ids_.front();\n";
  out << "    for (std::size_t i = 0; i < active_ids_.size(); ++i) {\n";
  out << "      const float* active_vec = active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "      double dot_qc = dot_product(vector, active_vec, model_.dim);\n";
  out << "      double d2 = l2_dist2_from_dot(query_norm2, active_norm2_[i], dot_qc);\n";
  out << "      if (d2 < best_d2) {\n";
  out << "        best_d2 = d2;\n";
  out << "        best_id = active_ids_[i];\n";
  out << "      }\n";
  out << "    }\n";
  out << "    if (!std::isfinite(best_d2)) {\n";
  out << "      if (cache_token) {\n";
  out << "        *cache_token = 0;\n";
  out << "      }\n";
  out << "      return false;\n";
  out << "    }\n";
  out << "    *centroid = best_id;\n";
  out << "    *dist2 = best_d2;\n";
  out << "    if (cache_token) {\n";
  out << "      *cache_token = 0;\n";
  out << "    }\n";
  out << "    return true;\n";
  out << "  }\n";
  out << "\n";
  out << "  std::size_t active_count = index_active_ids_.size();\n";
  out << "  std::size_t pivot_count = index_pivot_ids_.size();\n";
  out << "  const std::vector<double>& query_pivot_l2 = prepare_query_pivot_l2(\n";
  out << "      vector,\n";
  out << "      query_norm2,\n";
  out << "      cache_token ? *cache_token : 0,\n";
  out << "      cache_token,\n";
  out << "      false);\n";
  out << "\n";
  out << "  double best_d2 = std::numeric_limits<double>::infinity();\n";
  out << "  uint32_t best_id = index_active_ids_.front();\n";
  out << "  for (std::size_t i = 0; i < active_count; ++i) {\n";
  out << "    const float* row = index_centroid_pivot_l2_.data() + i * pivot_count;\n";
  out << "    double lower_bound2 = 0.0;\n";
  out << "    bool pruned = false;\n";
  out << "    for (std::size_t p = 0; p < pivot_count; ++p) {\n";
  out << "      double delta = std::fabs(query_pivot_l2[p] - static_cast<double>(row[p]));\n";
  out << "      double delta2 = delta * delta;\n";
  out << "      if (delta2 > lower_bound2) {\n";
  out << "        lower_bound2 = delta2;\n";
  out << "      }\n";
  out << "      if (lower_bound2 >= best_d2) {\n";
  out << "        pruned = true;\n";
  out << "        break;\n";
  out << "      }\n";
  out << "    }\n";
  out << "    if (pruned) {\n";
  out << "      continue;\n";
  out << "    }\n";
  out << "    const float* active_vec = index_active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "    double dot_qc = dot_product(vector, active_vec, model_.dim);\n";
  out << "    double d2 = l2_dist2_from_dot(query_norm2, index_active_norm2_[i], dot_qc);\n";
  out << "    if (d2 < best_d2) {\n";
  out << "      best_d2 = d2;\n";
  out << "      best_id = index_active_ids_[i];\n";
  out << "    }\n";
  out << "  }\n";
  out << "\n";
  out << "  if (!std::isfinite(best_d2)) {\n";
  out << "    if (cache_token) {\n";
  out << "      *cache_token = 0;\n";
  out << "    }\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  *centroid = best_id;\n";
  out << "  *dist2 = best_d2;\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "uint32_t Hasher::dim() const {\n";
  out << "  if (!loaded_) throw std::runtime_error(\"Hasher not loaded\");\n";
  out << "  return model_.dim;\n";
  out << "}\n\n";
  out << "uint32_t Hasher::hash_bits() const {\n";
  out << "  if (!loaded_) throw std::runtime_error(\"Hasher not loaded\");\n";
  out << "  return model_.hash_bits;\n";
  out << "}\n\n";
  out << "bool Hasher::nearest_active_centroid(const float* vector,\n";
  out << "                                   uint32_t* centroid,\n";
  out << "                                   float* dist2,\n";
  out << "                                   uint64_t* cache_token) const {\n";
  out << "  double d2 = 0.0;\n";
  out << "  if (!nearest_centroid(vector, centroid, &d2, cache_token)) {\n";
  out << "    if (cache_token) {\n";
  out << "      *cache_token = 0;\n";
  out << "    }\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  if (dist2) {\n";
  out << "    *dist2 = static_cast<float>(d2);\n";
  out << "  }\n";
  out << "  return true;\n";
  out << "}\n\n";
  out << "Hash256 Hasher::hash(const float* vector) const {\n";
  out << "  if (!loaded_) throw std::runtime_error(\"Hasher not loaded\");\n";
  out << "  if (!vector) throw std::runtime_error(\"Input vector is null\");\n";
  out << "  uint32_t centroid = 0;\n";
  out << "  double dist2 = 0.0;\n";
  out << "  vortex::HashOutput result;\n";
  out << "  if (nearest_centroid(vector, &centroid, &dist2, nullptr)) {\n";
  out << "    result = model_.hash_from_centroid(centroid, dist2);\n";
  out << "  } else {\n";
  out << "    result = model_.hash(vector);\n";
  out << "  }\n";
  out << "  Hash256 out{};\n";
  out << "  out.words = result.value.words;\n";
  out << "  return out;\n";
  out << "}\n\n";
  out << "HashCentroidResult Hasher::hash_with_centroid(const float* vector) const {\n";
  out << "  if (!loaded_) throw std::runtime_error(\"Hasher not loaded\");\n";
  out << "  if (!vector) throw std::runtime_error(\"Input vector is null\");\n";
  out << "  HashCentroidResult out{};\n";
  out << "  double dist2 = 0.0;\n";
  out << "  if (nearest_centroid(vector, &out.centroid, &dist2, &out.cache_token)) {\n";
  out << "    auto result = model_.hash_from_centroid(out.centroid, dist2);\n";
  out << "    out.hash.words = result.value.words;\n";
  out << "    out.dist2 = static_cast<float>(dist2);\n";
  out << "    return out;\n";
  out << "  }\n";
  out << "  auto nearest = model_.router.nearest(vector);\n";
  out << "  auto result = model_.hash_from_centroid(nearest.centroid, nearest.dist2);\n";
  out << "  out.hash.words = result.value.words;\n";
  out << "  out.centroid = nearest.centroid;\n";
  out << "  out.dist2 = static_cast<float>(nearest.dist2);\n";
  out << "  out.cache_token = 0;\n";
  out << "  return out;\n";
  out << "}\n\n";
  out << "uint64_t Hasher::hash64(const float* vector) const {\n";
  out << "  if (!loaded_) throw std::runtime_error(\"Hasher not loaded\");\n";
  out << "  if (model_.hash_bits > 64) throw std::runtime_error(\"hash_bits > 64\");\n";
  out << "  return hash(vector).words[0];\n";
  out << "}\n\n";
  out << "bool Hasher::ann_query(const float* vector,\n";
  out << "                      uint32_t k,\n";
  out << "                      std::vector<AnnNeighbor>* out,\n";
  out << "                      uint64_t cache_token) const {\n";
  out << "  if (!out) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  out->clear();\n";
  out << "  if (!loaded_ || !vector || k == 0 || active_ids_.empty()) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::size_t requested = std::min<std::size_t>(k, active_ids_.size());\n";
  out << "  if (requested == 0) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  double query_norm2 = l2_norm2(vector, model_.dim);\n";
  out << "  if (!std::isfinite(query_norm2)) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  auto cmp_neighbor = [](const AnnNeighbor& a, const AnnNeighbor& b) {\n";
  out << "    return a.dist2 < b.dist2;\n";
  out << "  };\n";
  out << "  auto& cache_state = tls_query_pivot_cache();\n";
  out << "\n";
  out << "  if (!use_centroid_index_for_queries() ||\n";
  out << "      index_centroid_pivot_l2_.size() != index_active_ids_.size() * index_pivot_ids_.size()) {\n";
  out << "    auto& full_scan = cache_state.ann_full_scan;\n";
  out << "    if (full_scan.size() != active_ids_.size()) {\n";
  out << "      full_scan.resize(active_ids_.size());\n";
  out << "    }\n";
  out << "    for (std::size_t i = 0; i < active_ids_.size(); ++i) {\n";
  out << "      const float* active_vec = active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "      double dot_qc = dot_product(vector, active_vec, model_.dim);\n";
  out << "      double d2 = l2_dist2_from_dot(query_norm2, active_norm2_[i], dot_qc);\n";
  out << "      full_scan[i] = AnnNeighbor{active_ids_[i], static_cast<float>(d2)};\n";
  out << "    }\n";
  out << "    auto begin = full_scan.begin();\n";
  out << "    auto middle = begin + static_cast<std::ptrdiff_t>(requested);\n";
  out << "    if (full_scan.size() > requested) {\n";
  out << "      std::nth_element(begin, middle, full_scan.end(), cmp_neighbor);\n";
  out << "    } else {\n";
  out << "      middle = full_scan.end();\n";
  out << "    }\n";
  out << "    std::sort(begin, middle, cmp_neighbor);\n";
  out << "    out->assign(begin, middle);\n";
  out << "    return !out->empty();\n";
  out << "  }\n";
  out << "\n";
  out << "  auto heap_cmp = [](const AnnHeapEntry& a, const AnnHeapEntry& b) {\n";
  out << "    return a.dist2 < b.dist2;\n";
  out << "  };\n";
  out << "  auto& heap = cache_state.ann_heap;\n";
  out << "  heap.clear();\n";
  out << "  if (heap.capacity() < requested) {\n";
  out << "    heap.reserve(requested);\n";
  out << "  }\n";
  out << "  bool heap_ready = false;\n";
  out << "\n";
  out << "  std::size_t pivot_count = index_pivot_ids_.size();\n";
  out << "  const std::vector<double>& query_pivot_l2 = prepare_query_pivot_l2(\n";
  out << "      vector,\n";
  out << "      query_norm2,\n";
  out << "      cache_token,\n";
  out << "      nullptr,\n";
  out << "      true);\n";
  out << "\n";
  out << "  for (std::size_t i = 0; i < index_active_ids_.size(); ++i) {\n";
  out << "    double cutoff = heap_ready ? heap.front().dist2 : std::numeric_limits<double>::infinity();\n";
  out << "    const float* row = index_centroid_pivot_l2_.data() + i * pivot_count;\n";
  out << "    double lower_bound2 = 0.0;\n";
  out << "    bool pruned = false;\n";
  out << "    for (std::size_t p = 0; p < pivot_count; ++p) {\n";
  out << "      double delta = std::fabs(query_pivot_l2[p] - static_cast<double>(row[p]));\n";
  out << "      double delta2 = delta * delta;\n";
  out << "      if (delta2 > lower_bound2) {\n";
  out << "        lower_bound2 = delta2;\n";
  out << "      }\n";
  out << "      if (lower_bound2 >= cutoff) {\n";
  out << "        pruned = true;\n";
  out << "        break;\n";
  out << "      }\n";
  out << "    }\n";
  out << "    if (pruned) {\n";
  out << "      continue;\n";
  out << "    }\n";
  out << "    const float* active_vec = index_active_vectors_.data() + i * static_cast<std::size_t>(model_.dim);\n";
  out << "    double dot_qc = dot_product(vector, active_vec, model_.dim);\n";
  out << "    double d2 = l2_dist2_from_dot(query_norm2, index_active_norm2_[i], dot_qc);\n";
  out << "    uint32_t cid = index_active_ids_[i];\n";
  out << "    if (heap.size() < requested) {\n";
  out << "      heap.push_back(AnnHeapEntry{d2, cid});\n";
  out << "      if (heap.size() == requested) {\n";
  out << "        std::make_heap(heap.begin(), heap.end(), heap_cmp);\n";
  out << "        heap_ready = true;\n";
  out << "      }\n";
  out << "    } else if (d2 < heap.front().dist2) {\n";
  out << "      std::pop_heap(heap.begin(), heap.end(), heap_cmp);\n";
  out << "      heap.back() = AnnHeapEntry{d2, cid};\n";
  out << "      std::push_heap(heap.begin(), heap.end(), heap_cmp);\n";
  out << "    }\n";
  out << "  }\n";
  out << "\n";
  out << "  if (heap.empty()) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  std::sort(heap.begin(), heap.end(), heap_cmp);\n";
  out << "  out->resize(heap.size());\n";
  out << "  for (std::size_t i = 0; i < heap.size(); ++i) {\n";
  out << "    (*out)[i] = AnnNeighbor{heap[i].centroid, static_cast<float>(heap[i].dist2)};\n";
  out << "  }\n";
  out << "  return !out->empty();\n";
  out << "}\n\n";
  out << "} // namespace " << ident << "\n";
  out << "} // namespace vortex_codegen\n\n";
  out << "static vortex_codegen::" << ident << "::Hasher g_hasher;\n\n";
  out << "extern \"C\" {\n";
  out << "const char* " << prefix << "_infer_name() {\n";
  out << "  return \"" << escaped_name << "\";\n";
  out << "}\n\n";
  out << "bool " << prefix << "_infer_load_ex2(const char* model_path,\n";
  out << "                          int enable_centroid_index,\n";
  out << "                          uint32_t centroid_index_pivots,\n";
  out << "                          int enable_query_cache) {\n";
  out << "  try {\n";
  out << "    std::filesystem::path resolved = vortex_codegen::" << ident
      << "::resolve_model_path(model_path);\n";
  out << "    vortex_codegen::" << ident << "::LoadOptions options;\n";
  out << "    options.enable_centroid_index = (enable_centroid_index != 0);\n";
  out << "    options.centroid_index_pivots = centroid_index_pivots;\n";
  out << "    options.enable_query_cache = (enable_query_cache != 0);\n";
  out << "    return g_hasher.load(resolved, options);\n";
  out << "  } catch (...) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "}\n\n";
  out << "bool " << prefix << "_infer_load_ex(const char* model_path,\n";
  out << "                         int enable_centroid_index,\n";
  out << "                         uint32_t centroid_index_pivots) {\n";
  out << "  return " << prefix << "_infer_load_ex2(\n";
  out << "      model_path,\n";
  out << "      enable_centroid_index,\n";
  out << "      centroid_index_pivots,\n";
  out << "      1);\n";
  out << "}\n\n";
  out << "bool " << prefix << "_infer_load(const char* model_path) {\n";
  out << "  return " << prefix << "_infer_load_ex2(\n";
  out << "      model_path,\n";
  out << "      1,\n";
  out << "      vortex_codegen::" << ident << "::kDefaultCentroidIndexPivots,\n";
  out << "      1);\n";
  out << "}\n\n";
  out << "void " << prefix << "_infer_cleanup() {\n";
  out << "  g_hasher.unload();\n";
  out << "}\n\n";
  out << "uint32_t " << prefix << "_infer_dim() {\n";
  out << "  try {\n";
  out << "    return g_hasher.dim();\n";
  out << "  } catch (...) {\n";
  out << "    return 0;\n";
  out << "  }\n";
  out << "}\n\n";
  out << "uint32_t " << prefix << "_infer_hash_bits() {\n";
  out << "  try {\n";
  out << "    return g_hasher.hash_bits();\n";
  out << "  } catch (...) {\n";
  out << "    return 0;\n";
  out << "  }\n";
  out << "}\n\n";
  out << "bool " << prefix << "_infer_hash(const float* vector, uint64_t out_words[4]) {\n";
  out << "  if (!out_words) return false;\n";
  out << "  try {\n";
  out << "    auto hash = g_hasher.hash(vector);\n";
  out << "    out_words[0] = hash.words[0];\n";
  out << "    out_words[1] = hash.words[1];\n";
  out << "    out_words[2] = hash.words[2];\n";
  out << "    out_words[3] = hash.words[3];\n";
  out << "    return true;\n";
  out << "  } catch (...) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "}\n\n";
  out << "uint64_t " << prefix << "_infer_hash64(const float* vector, int* ok) {\n";
  out << "  if (ok) *ok = 0;\n";
  out << "  try {\n";
  out << "    uint64_t value = g_hasher.hash64(vector);\n";
  out << "    if (ok) *ok = 1;\n";
  out << "    return value;\n";
  out << "  } catch (...) {\n";
  out << "    return 0;\n";
  out << "  }\n";
  out << "}\n";
  out << "\n";
  out << "bool " << prefix << "_infer_nearest_active_centroid(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t* out_centroid,\n";
  out << "    float* out_dist2,\n";
  out << "    uint64_t* out_cache_token) {\n";
  out << "  if (!out_centroid || !out_dist2) {\n";
  out << "    if (out_cache_token) *out_cache_token = 0;\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  try {\n";
  out << "    return g_hasher.nearest_active_centroid(vector, out_centroid, out_dist2, out_cache_token);\n";
  out << "  } catch (...) {\n";
  out << "    if (out_cache_token) *out_cache_token = 0;\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "}\n";
  out << "\n";
  out << "bool " << prefix << "_infer_hash_with_centroid(\n";
  out << "    const float* vector,\n";
  out << "    uint64_t out_words[4],\n";
  out << "    uint32_t* out_centroid,\n";
  out << "    float* out_dist2,\n";
  out << "    uint64_t* out_cache_token) {\n";
  out << "  if (!out_words || !out_centroid || !out_dist2) {\n";
  out << "    if (out_cache_token) *out_cache_token = 0;\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  try {\n";
  out << "    auto result = g_hasher.hash_with_centroid(vector);\n";
  out << "    out_words[0] = result.hash.words[0];\n";
  out << "    out_words[1] = result.hash.words[1];\n";
  out << "    out_words[2] = result.hash.words[2];\n";
  out << "    out_words[3] = result.hash.words[3];\n";
  out << "    *out_centroid = result.centroid;\n";
  out << "    *out_dist2 = result.dist2;\n";
  out << "    if (out_cache_token) *out_cache_token = result.cache_token;\n";
  out << "    return true;\n";
  out << "  } catch (...) {\n";
  out << "    if (out_cache_token) *out_cache_token = 0;\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "}\n";
  out << "\n";
  out << "bool " << prefix << "_infer_ann_query_cached(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t k,\n";
  out << "    uint32_t* out_centroids,\n";
  out << "    float* out_dist2,\n";
  out << "    uint32_t capacity,\n";
  out << "    uint32_t* out_count,\n";
  out << "    uint64_t cache_token) {\n";
  out << "  if (out_count) *out_count = 0;\n";
  out << "  if (k == 0 || capacity == 0 || (!out_centroids && !out_dist2)) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "  try {\n";
  out << "    std::vector<vortex_codegen::" << ident << "::AnnNeighbor> neighbors;\n";
  out << "    if (!g_hasher.ann_query(vector, k, &neighbors, cache_token)) {\n";
  out << "      return false;\n";
  out << "    }\n";
  out << "    uint32_t count = static_cast<uint32_t>(neighbors.size());\n";
  out << "    if (count > capacity) {\n";
  out << "      count = capacity;\n";
  out << "    }\n";
  out << "    for (uint32_t i = 0; i < count; ++i) {\n";
  out << "      if (out_centroids) out_centroids[i] = neighbors[i].centroid;\n";
  out << "      if (out_dist2) out_dist2[i] = neighbors[i].dist2;\n";
  out << "    }\n";
  out << "    if (out_count) *out_count = count;\n";
  out << "    return count > 0;\n";
  out << "  } catch (...) {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "}\n";
  out << "\n";
  out << "bool " << prefix << "_infer_ann_query(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t k,\n";
  out << "    uint32_t* out_centroids,\n";
  out << "    float* out_dist2,\n";
  out << "    uint32_t capacity,\n";
  out << "    uint32_t* out_count) {\n";
  out << "  return " << prefix << "_infer_ann_query_cached(\n";
  out << "      vector,\n";
  out << "      k,\n";
  out << "      out_centroids,\n";
  out << "      out_dist2,\n";
  out << "      capacity,\n";
  out << "      out_count,\n";
  out << "      0);\n";
  out << "}\n";
  out << "} // extern \"C\"\n";
  return out.str();
}

} // namespace vortex::codegen_internal
