#include "codegen_internal.h"

#include <sstream>
#include <string>

namespace vortex::codegen_internal {

std::string generate_header(const std::string& ident) {
  std::ostringstream out;
  std::string guard = header_guard_for(ident);
  out << "#ifndef " << guard << "\n";
  out << "#define " << guard << "\n\n";
  out << "#include \"vortex_v1/model.h\"\n\n";
  out << "#include <array>\n";
  out << "#include <cstddef>\n";
  out << "#include <cstdint>\n";
  out << "#include <filesystem>\n";
  out << "#include <limits>\n";
  out << "#include <memory>\n";
  out << "#include <new>\n";
  out << "#include <type_traits>\n";
  out << "#include <vector>\n\n";
  out << "#if defined(_WIN32)\n";
  out << "#  define VORTEX_INFER_EXPORT __declspec(dllexport)\n";
  out << "#elif defined(__GNUC__)\n";
  out << "#  define VORTEX_INFER_EXPORT __attribute__((visibility(\"default\")))\n";
  out << "#else\n";
  out << "#  define VORTEX_INFER_EXPORT\n";
  out << "#endif\n\n";
  out << "namespace vortex_codegen {\n";
  out << "namespace " << ident << " {\n\n";
  out << "template <typename T, std::size_t Alignment>\n";
  out << "class AlignedAllocator {\n";
  out << " public:\n";
  out << "  using value_type = T;\n";
  out << "  using size_type = std::size_t;\n";
  out << "  using difference_type = std::ptrdiff_t;\n";
  out << "\n";
  out << "  AlignedAllocator() noexcept = default;\n";
  out << "  template <typename U>\n";
  out << "  AlignedAllocator(const AlignedAllocator<U, Alignment>&) noexcept {}\n";
  out << "\n";
  out << "  [[nodiscard]] T* allocate(std::size_t n) {\n";
  out << "    if (n > (std::numeric_limits<std::size_t>::max() / sizeof(T))) {\n";
  out << "      throw std::bad_alloc();\n";
  out << "    }\n";
  out << "    if (n == 0) {\n";
  out << "      return nullptr;\n";
  out << "    }\n";
  out << "#if defined(__cpp_aligned_new)\n";
  out << "    void* ptr = ::operator new(n * sizeof(T), std::align_val_t(Alignment));\n";
  out << "#else\n";
  out << "    void* ptr = ::operator new(n * sizeof(T));\n";
  out << "#endif\n";
  out << "    return static_cast<T*>(ptr);\n";
  out << "  }\n";
  out << "\n";
  out << "  void deallocate(T* ptr, std::size_t) noexcept {\n";
  out << "#if defined(__cpp_aligned_new)\n";
  out << "    ::operator delete(ptr, std::align_val_t(Alignment));\n";
  out << "#else\n";
  out << "    ::operator delete(ptr);\n";
  out << "#endif\n";
  out << "  }\n";
  out << "\n";
  out << "  template <typename U>\n";
  out << "  struct rebind {\n";
  out << "    using other = AlignedAllocator<U, Alignment>;\n";
  out << "  };\n";
  out << "\n";
  out << "  using is_always_equal = std::true_type;\n";
  out << "  using propagate_on_container_move_assignment = std::true_type;\n";
  out << "\n";
  out << "  template <typename U>\n";
  out << "  bool operator==(const AlignedAllocator<U, Alignment>&) const noexcept {\n";
  out << "    return true;\n";
  out << "  }\n";
  out << "\n";
  out << "  template <typename U>\n";
  out << "  bool operator!=(const AlignedAllocator<U, Alignment>&) const noexcept {\n";
  out << "    return false;\n";
  out << "  }\n";
  out << "};\n\n";
  out << "template <typename T>\n";
  out << "using AlignedVector = std::vector<T, AlignedAllocator<T, 64>>;\n\n";
  out << "struct Hash256 {\n";
  out << "  std::array<uint64_t, 4> words{};\n";
  out << "};\n\n";
  out << "struct LoadOptions {\n";
  out << "  bool enable_centroid_index = true;\n";
  out << "  uint32_t centroid_index_pivots = 16;\n";
  out << "  bool enable_query_cache = true;\n";
  out << "};\n\n";
  out << "struct AnnNeighbor {\n";
  out << "  uint32_t centroid = 0;\n";
  out << "  float dist2 = 0.0f;\n";
  out << "};\n\n";
  out << "struct HashCentroidResult {\n";
  out << "  Hash256 hash{};\n";
  out << "  uint32_t centroid = 0;\n";
  out << "  float dist2 = 0.0f;\n";
  out << "  uint64_t cache_token = 0;\n";
  out << "};\n\n";
  out << "class Hasher {\n";
  out << " public:\n";
  out << "  bool load(const std::filesystem::path& model_path,\n";
  out << "            const LoadOptions& options = LoadOptions{});\n";
  out << "  bool load_from_dir(const std::filesystem::path& dir,\n";
  out << "                     const LoadOptions& options = LoadOptions{});\n";
  out << "  void unload();\n";
  out << "  bool loaded() const;\n";
  out << "  bool centroid_index_enabled() const;\n";
  out << "  bool query_cache_enabled() const;\n";
  out << "  uint32_t dim() const;\n";
  out << "  uint32_t hash_bits() const;\n";
  out << "  Hash256 hash(const float* vector) const;\n";
  out << "  HashCentroidResult hash_with_centroid(const float* vector) const;\n";
  out << "  uint64_t hash64(const float* vector) const;\n\n";
  out << "  bool nearest_active_centroid(const float* vector,\n";
  out << "                              uint32_t* centroid,\n";
  out << "                              float* dist2,\n";
  out << "                              uint64_t* cache_token = nullptr) const;\n\n";
  out << "  bool ann_query(const float* vector,\n";
  out << "                 uint32_t k,\n";
  out << "                 std::vector<AnnNeighbor>* out,\n";
  out << "                 uint64_t cache_token = 0) const;\n\n";
  out << " private:\n";
  out << "  bool nearest_centroid(const float* vector,\n";
  out << "                        uint32_t* centroid,\n";
  out << "                        double* dist2,\n";
  out << "                        uint64_t* cache_token) const;\n";
  out << "  bool should_consider_centroid_index() const;\n";
  out << "  bool use_centroid_index_for_queries() const;\n";
  out << "  bool load_centroid_index(const std::filesystem::path& index_path,\n";
  out << "                           uint32_t expected_pivots);\n";
  out << "  void populate_centroid_buffers(const std::vector<uint32_t>& ids,\n";
  out << "                                 AlignedVector<float>* vectors,\n";
  out << "                                 std::vector<double>* norm2) const;\n";
  out << "  const std::vector<double>& prepare_query_pivot_l2(\n";
  out << "      const float* vector,\n";
  out << "      double query_norm2,\n";
  out << "      uint64_t input_cache_token,\n";
  out << "      uint64_t* out_cache_token,\n";
  out << "      bool allow_cache_without_output) const;\n";
  out << "  void prepare_active_centroids();\n";
  out << "  void clear_active_centroids();\n";
  out << "  void build_centroid_index(uint32_t pivot_count);\n";
  out << "  void clear_centroid_index();\n";
  out << "  vortex::VortexModel model_{};\n";
  out << "  bool centroid_index_enabled_ = true;\n";
  out << "  bool query_cache_enabled_ = true;\n";
  out << "  std::vector<uint32_t> active_ids_;\n";
  out << "  AlignedVector<float> active_vectors_;\n";
  out << "  std::vector<double> active_norm2_;\n";
  out << "  std::vector<double> centroid_norm2_;\n";
  out << "  std::vector<uint32_t> index_active_ids_;\n";
  out << "  AlignedVector<float> index_active_vectors_;\n";
  out << "  std::vector<double> index_active_norm2_;\n";
  out << "  std::vector<uint32_t> index_pivot_ids_;\n";
  out << "  AlignedVector<float> index_pivot_vectors_;\n";
  out << "  std::vector<double> index_pivot_norm2_;\n";
  out << "  AlignedVector<float> index_centroid_pivot_l2_;\n";
  out << "  bool loaded_ = false;\n";
  out << "};\n\n";
  out << "} // namespace " << ident << "\n";
  out << "} // namespace vortex_codegen\n\n";
  std::string prefix = ident + "_vortex";
  out << "extern \"C\" {\n";
  out << "VORTEX_INFER_EXPORT const char* " << prefix << "_infer_name();\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_load_ex2(\n";
  out << "    const char* model_path,\n";
  out << "    int enable_centroid_index,\n";
  out << "    uint32_t centroid_index_pivots,\n";
  out << "    int enable_query_cache);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_load_ex(\n";
  out << "    const char* model_path,\n";
  out << "    int enable_centroid_index,\n";
  out << "    uint32_t centroid_index_pivots);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_load(const char* model_path);\n";
  out << "VORTEX_INFER_EXPORT void " << prefix << "_infer_cleanup();\n";
  out << "VORTEX_INFER_EXPORT uint32_t " << prefix << "_infer_dim();\n";
  out << "VORTEX_INFER_EXPORT uint32_t " << prefix << "_infer_hash_bits();\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_hash(const float* vector,\n";
  out << "                                       uint64_t out_words[4]);\n";
  out << "VORTEX_INFER_EXPORT uint64_t " << prefix << "_infer_hash64(const float* vector,\n";
  out << "                                          int* ok);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_nearest_active_centroid(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t* out_centroid,\n";
  out << "    float* out_dist2,\n";
  out << "    uint64_t* out_cache_token);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_hash_with_centroid(\n";
  out << "    const float* vector,\n";
  out << "    uint64_t out_words[4],\n";
  out << "    uint32_t* out_centroid,\n";
  out << "    float* out_dist2,\n";
  out << "    uint64_t* out_cache_token);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_ann_query(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t k,\n";
  out << "    uint32_t* out_centroids,\n";
  out << "    float* out_dist2,\n";
  out << "    uint32_t capacity,\n";
  out << "    uint32_t* out_count);\n";
  out << "VORTEX_INFER_EXPORT bool " << prefix << "_infer_ann_query_cached(\n";
  out << "    const float* vector,\n";
  out << "    uint32_t k,\n";
  out << "    uint32_t* out_centroids,\n";
  out << "    float* out_dist2,\n";
  out << "    uint32_t capacity,\n";
  out << "    uint32_t* out_count,\n";
  out << "    uint64_t cache_token);\n";
  out << "} // extern \"C\"\n\n";
  out << "#endif // " << guard << "\n";
  return out.str();
}

} // namespace vortex::codegen_internal
